[package]
name = "frontend"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dev-dependencies]
wasm-bindgen-test = "0.3.19"

[dependencies.web-sys]
version = "*"
features = [
  'HtmlAudioElement',
]

[dependencies]
zoon.workspace = true
