[package]
version = "0.1.0"
name = "frontend"
repository = "https://github.com/MoonZoon/MoonZoon"
authors = ["Martin Kavík <martin@kavik.cz>"]
description = "Timer - MoonZoon example"
categories = ["MoonZoon", "example"]
license = "MIT"
readme = "../README.md"
edition = "2021"

[dev-dependencies]
wasm-bindgen-test = "0.3.19"

[dependencies.web-sys]
version = "*"
features = [
  'HtmlAudioElement',
]

[dependencies]
zoon = { git = "https://github.com/MoonZoon/MoonZoon", rev = "457b8d1" }

