[package]
version = "0.1.0"
name = "frontend"
repository = "https://github.com/MoonZoon/MoonZoon"
authors = ["Martin Kavík <martin@kavik.cz>"]
description = "Timer - MoonZoon example"
categories = ["MoonZoon", "example"]
license = "MIT"
readme = "../README.md"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
wasm-bindgen-test = "0.3.19"

[dependencies.web-sys]
version = "*"
features = [
  'HtmlAudioElement',
]

[dependencies]
zoon = { git = "https://github.com/MoonZoon/MoonZoon", rev = "457b8d1" }

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Os']
